version: '3'
services:
        ias:
                image: idscan_ias
                user: 1001:1001
                build: 
                        context: .
                        dockerfile: Dockerfile                        
                depends_on:
                        - redis
                        - rabbitmq
                        - flower
                        - gpu_worker
                        - cpu_worker
                environment:
                        - IAS_SKIP_GPU_CHECK
                volumes:
                       - .:/home/appuser
                network_mode: host
                expose: 
                    - "8080"
                command: python -m ias.swagger_server
        cpu_worker:
                image: idscan_cpu_worker
                user: 1001:1001
                build: 
                        context: .
                        dockerfile: ias/tasks/cpu_tasks/Dockerfile
                volumes:
                        - .:/ias
                network_mode: host
                entrypoint: celery -A ias.tasks.cpu_tasks worker --concurrency=2 -Ofair --loglevel=info -Q cpu_tasks
        gpu_worker:
                image: idscan_gpu_worker
                user: 1001:1001
                build: 
                  context: .
                  dockerfile: ias/tasks/gpu_tasks/Dockerfile
                deploy:
                  resources:
                    reservations:
                      devices:
                      - driver: nvidia
                        capabilities: [compute]
                volumes:
                  - .:/ias
                network_mode: host
                entrypoint: celery -A ias.tasks.gpu_tasks worker --concurrency=1 -Ofair --loglevel=info -Q gpu_tasks
        flower:
                image: mher/flower
                user: 1001:1001
                depends_on:
                    - redis
                expose:
                    - "5555"
                entrypoint: flower --broker=amqp://guest:guest@localhost:5672//
                network_mode: host
        redis:
                image: redis
                network_mode: host
                expose: 
                    - "6379"
        rabbitmq:
                image: rabbitmq
                user: 1001:1001
                network_mode: host
                volumes:
                        - ./rabbitmq:/etc/rabbitmq
                entrypoint: rabbitmq-server
                expose:
                    - "5672"
                    - "15672"
                    - "61613"
#         nginx:
#                 image: nginx
#                 depends_on:
#                     - server
#                 network_mode: host
#                 expose: 
#                    - "80"
#                    - "443"
#                 volumes:
#                         - ${SORTIES_PATH}:/sorties
#                         - ${APP_PATH}:/app
#                         - ${SRTM_PATH}:/root/.srtm
#                         - ./nginx/conf.d:/etc/nginx/conf.d
#                         - ../detweb-frontend/build:/frontend
#                         - uwsgi-sockets:/tmp
# volumes:
#     uwsgi-sockets:  



