#FROM mcr.microsoft.com/vscode/devcontainers/python:3 AS base
FROM pytorch/pytorch AS base
# Setup env
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1


FROM base AS python-deps

# Install pipenv and compilation dependencies
RUN pip install pipenv
RUN pip install pipx
RUN apt-get update && apt-get install -y --no-install-recommends gcc git

WORKDIR /workspaces
RUN printf '%s\n' 'default_context:' '  project_name: "ias"' > .cookiecutterrc
RUN pipx run cookiecutter --config-file .cookiecutterrc --no-input gh:sourcery-ai/python-best-practices-cookiecutter
WORKDIR /workspaces/ias
RUN git init
RUN mkdir .venv
RUN pipenv install --dev

# Install python dependencies in /.venv
COPY Pipfile .
COPY Pipfile.lock .
RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --dev
ENV PATH="/workspaces/ias/.venv/bin:$PATH"
ENV PIPENV_VERBOSITY=-1
RUN pipx install pre-commit
RUN pre-commit install -t pre-commit
RUN pre-commit install -t pre-push